# **************** Domain monitoring application ****************
# This application used to monitor life cycle of domain
# it has multiple service : MongoDB, RabbitMQ , Load balancer , Application
version: '3.8'
services:
# **************** MongoDB ****************
  mongodb:
    image: mongo:latest
    container_name: mongodatabase_1
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data_1:/data/db
    networks:
      - app-network_1


# **************** Application ****************
  app:
    build: .
    container_name: marmar_container
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: secret
      MONGO_HOSTNAME: "10.90.78.133"
      MONGO_PORT: 27018
      MONGO_DB: mydatabase
      LIMIT: 10
    networks:
      - app-network_1

# **************** Volume ****************
volumes:
  mongodb_data_1:

# **************** Network ****************
networks:
  app-network_1:
    driver: bridge
