# **************** Domain monitoring application ****************
# This application used to monitor life cycle of domain
# it has multiple service : MongoDB, RabbitMQ , Load balancer , Application
version: '3.8'
services:
# **************** MongoDB ****************
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network


# **************** Application ****************
  app:
    platform: "linux/amd64"
    build: .
    container_name: nrd_feed_getter
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: secret
      MONGO_HOSTNAME: mongodb
      MONGO_PORT: 27017
      MONGO_DB: mydatabase
    ports:
      - "80:80"
    networks:
      - app-network

# **************** Volume ****************
volumes:
  mongodb_data:

# **************** Network ****************
networks:
  app-network:
    driver: bridge
